runtime: python312
service: pixaris-app
entrypoint: python app.py

instance_class: F4_1G
env_variables:
  GRADIO_SERVER_NAME: "0.0.0.0"
  GRADIO_SERVER_PORT: "8080"

automatic_scaling:
  target_cpu_utilization: 0.95
  min_pending_latency: 3000ms
  max_concurrent_requests: 200

handlers:
  - url: /.*
    script: auto